1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
enhance Python's capabilities for numerical operations
Ans) NumPy is a powerful Python library for scientific computing that enhances Python's ability to handle numerical data. It provides:

Efficient Array Operations: NumPy arrays are faster and more memory-efficient than Python lists, especially for large datasets.
Mathematical Functions: It offers a wide range of mathematical functions for linear algebra, statistics, and more, all optimized for speed.
Multidimensional Arrays: Supports complex, multi-dimensional arrays for data representation.
Broadcasting: Allows operations on arrays of different shapes without explicit loops.
Integration: Works seamlessly with other libraries like Pandas, SciPy, and Matplotlib, forming the backbone of many data analysis and machine learning workflows.?

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other
Ans) ?The np.mean() and np.average() functions in NumPy both calculate the average of array elements, but they differ in functionality. np.mean() computes the arithmetic mean without any weights, making it ideal for simple, unweighted averages. On the other hand, np.average() allows for weighted averaging, where different elements can be assigned varying levels of importance using the weights argument. If you only need a basic average, np.mean() is sufficient, but if you require the flexibility to apply different weights or need additional control over the calculation (e.g., along a specific axis), np.average() is the better choice.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays
Ans) 1. Reversing a 1D Array
For a 1D array, you can reverse it by using slicing with the [::-1] syntax. This reverses the entire array.
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]

2. Reversing a 2D Array along Different Axes
For a 2D array, you can reverse along different axes (rows or columns) by slicing accordingly.
Reversing along the rows (vertical axis, axis=0):
reverse the rows by using slicing like [::-1, :], which reverses the rows while keeping the columns intact.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reversing along the rows (axis=0)
reversed_rows = arr_2d[::-1, :]

print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]
 

Q4.  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
in memory management and performance
Ans) 
Importance of Data Types in Memory Management and Performance
Memory Efficiency:

Data types define how much memory each element in the array occupies. For example, an int32 takes up 4 bytes, while an int64 takes 8 bytes.
By using a smaller or more appropriate data type, you can save memory, especially when working with large datasets.
Performance:

NumPy operations are optimized for specific data types. Using the appropriate data type can lead to faster computations. For instance, operations on float32 arrays can be faster than on float64 arrays due to lower memory usage and smaller size.
Operations on arrays with compatible types (e.g., both integer arrays or both float arrays) can be performed more efficiently. In contrast, type conversions (like from float64 to int32) may introduce overhead and degrade performance.
Precision and Range:

The choice of data type affects the precision and range of values that can be represented. For example, int32 can represent a smaller range of values than int64, but it uses less memory.
For floating-point arrays, float32 has lower precision than float64. If high precision is required, float64 is preferred despite the additional memory cost..

Q5.In NumPy, ndarrays (short for N-dimensional arrays) are the core data structure, representing multi-dimensional, homogeneous arrays. An ndarray is essentially a grid of values, all of the same data type, organized along axes, and it supports efficient operations over these values.

Key Features of ndarrays:
Homogeneous Data:

All elements in a NumPy array must have the same data type (e.g., all integers, all floats).
Multidimensional:

ndarrays can represent one-dimensional (1D) arrays, two-dimensional (2D) arrays, and higher-dimensional arrays (N-dimensional), making them versatile for a wide range of applications.
Fixed Size:

The size of an ndarray is fixed upon creation, and it cannot be resized directly. To change the size, you must create a new array with the desired dimensions.
Efficient Memory Management:

NumPy arrays are more memory-efficient than Python lists, especially for large datasets. The elements are stored in contiguous blocks of memory, making operations faster and more memory-efficient.
Vectorized Operations:

NumPy supports element-wise operations (e.g., addition, multiplication) directly on arrays without needing explicit loops, which leads to more concise and faster code.
Broadcasting:

Broadcasting allows NumPy to perform operations on arrays of different shapes, automatically adjusting their dimensions to match in certain situations.
Integration with Other Libraries:

ndarrays serve as the foundation for other libraries, such as Pandas (for DataFrames) and SciPy, making it easier to work with large datasets in scientific computing.

In NumPy, ndarrays (short for N-dimensional arrays) are the core data structure, representing multi-dimensional, homogeneous arrays. An ndarray is essentially a grid of values, all of the same data type, organized along axes, and it supports efficient operations over these values.

Key Features of ndarrays:
Homogeneous Data:

All elements in a NumPy array must have the same data type (e.g., all integers, all floats).
Multidimensional:

ndarrays can represent one-dimensional (1D) arrays, two-dimensional (2D) arrays, and higher-dimensional arrays (N-dimensional), making them versatile for a wide range of applications.
Fixed Size:

The size of an ndarray is fixed upon creation, and it cannot be resized directly. To change the size, you must create a new array with the desired dimensions.
Efficient Memory Management:

NumPy arrays are more memory-efficient than Python lists, especially for large datasets. The elements are stored in contiguous blocks of memory, making operations faster and more memory-efficient.
Vectorized Operations:

NumPy supports element-wise operations (e.g., addition, multiplication) directly on arrays without needing explicit loops, which leads to more concise and faster code.
Broadcasting:

Broadcasting allows NumPy to perform operations on arrays of different shapes, automatically adjusting their dimensions to match in certain situations.
Integration with Other Libraries:

ndarrays serve as the foundation for other libraries, such as Pandas (for DataFrames) and SciPy, making it easier to work with large datasets in scientific computing.


Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
Ans) NumPy arrays offer several performance benefits over Python lists, particularly when dealing with large-scale numerical operations. These advantages stem from NumPy's optimized design, which is focused on efficient memory management, computation speed, and the ability to handle large datasets. Here are the key performance benefits:

1. Memory Efficiency
Contiguous Memory Allocation:
NumPy arrays store data in contiguous memory blocks, which improves cache locality and reduces the overhead associated with managing individual elements. In contrast, Python lists are arrays of pointers to objects, which introduces additional memory overhead.
Fixed Data Types:
NumPy arrays are homogeneous, meaning all elements must be of the same data type. This allows NumPy to use a fixed memory size for each element (e.g., 8 bytes for float64), avoiding the overhead of storing metadata for each element, as in Python lists where each element is a separate object with type information.
2. Faster Computation
Vectorization:
NumPy performs operations on entire arrays in a single operation (known as vectorization). This avoids the need for explicit loops, which are inherently slower in Python. Operations like element-wise addition, multiplication, and other mathematical operations are highly optimized in NumPy, taking advantage of low-level implementations in C.
For example, adding two arrays with NumPy can be done in a single call, whereas Python lists would require a loop to perform the addition element by element, which is significantly slower.
Optimized Mathematical Functions:
NumPy functions are written in C and are optimized for performance, making them orders of magnitude faster than equivalent operations performed using Python loops. Functions like np.dot(), np.sum(), and np.mean() are highly optimized for array operations.
3. Broadcasting
Efficient Array Manipulation:
NumPy's broadcasting mechanism allows operations to be performed on arrays of different shapes without explicitly reshaping them. This leads to faster code and avoids the need for manual adjustments. In contrast, Python lists would require explicit loops or more complex logic to handle operations on arrays with different dimensions.
4. Low-Level Operations and Libraries
Integration with C and Fortran Libraries:
NumPy is integrated with low-level libraries written in C and Fortran, which provide highly efficient routines for matrix multiplication, linear algebra, statistics, and other numerical operations. This integration allows NumPy to leverage optimized, compiled code rather than relying on Python's interpreted execution.
Parallelization:
Some NumPy functions can be internally parallelized using multi-threading (via libraries like OpenBLAS), which speeds up computation on multi-core systems. Python lists cannot take advantage of this parallelism without manually managing threads or processes.
5. Less Overhead for Large Datasets
Handling Large Arrays:
NumPy can handle large datasets efficiently, both in terms of memory usage and speed. Python lists, on the other hand, are not as efficient when it comes to memory management for large datasets because each element in a list is a reference to a Python object, which introduces overhead.
Efficient Memory Layout:
NumPy uses a more efficient memory layout for large arrays, while Python lists can quickly become slow and inefficient when handling large volumes of data because each list element is a reference to a different Python object.


Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
output
Comparison of np.vstack() and np.hstack() in NumPy 
In NumPy, both vstack() and hstack() are functions used for stacking arrays, but they differ in the direction along which the stacking occurs. Understanding the theoretical concepts behind these functions can help clarify how and when to use them.

1. np.vstack(): Vertical Stacking
Purpose: vstack() stands for vertical stack. It stacks arrays along the vertical axis, meaning it adds more rows to an existing array.

How It Works: The function takes two or more arrays and combines them by appending the rows of one array to the rows of the other. The arrays must have the same number of columns in order to stack them vertically.

Mathematical Representation:

Let’s say you have two 2D arrays:
A = [[a, b], [c, d]] (2x2 array)
B = [[e, f], [g, h]] (2x2 array)
When you apply np.vstack([A, B]), the resulting array will have the rows of A followed by the rows of B:
Result = [[a, b], [c, d], [e, f], [g, h]] (4x2 array)
Conditions: The number of columns in the arrays must match, but the number of rows can be different.

2. np.hstack(): Horizontal Stacking
Purpose: hstack() stands for horizontal stack. It stacks arrays along the horizontal axis, meaning it adds more columns to an existing array.

How It Works: The function takes two or more arrays and combines them by appending the columns of one array to the columns of the other. The arrays must have the same number of rows in order to stack them horizontally.

Mathematical Representation:

Let’s say you have two 2D arrays:
A = [[a, b], [c, d]] (2x2 array)
B = [[e, f], [g, h]] (2x2 array)
When you apply np.hstack([A, B]), the resulting array will have the columns of B appended to the columns of A:
Result = [[a, b, e, f], [c, d, g, h]] (2x4 array)
Conditions: The number of rows in the arrays must match, but the number of columns can be different.
.

Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
Ans)
In NumPy, the methods fliplr() and flipud() are used to flip arrays along different axes, but they differ in the axis of flipping and their effect on the array’s orientation.

fliplr(): This method flips an array left-to-right, meaning it reverses the order of columns along the horizontal axis (axis 1). It is applicable to 2D arrays, where it swaps the columns in each row. For higher-dimensional arrays, fliplr() operates on the second axis (columns) of the array. For example, in a 2D array, fliplr() reverses the columns without changing the rows.

flipud(): In contrast, flipud() flips an array upside-down, meaning it reverses the order of rows along the vertical axis (axis 0). It swaps the rows of a 2D array, effectively flipping the array along the horizontal axis. For higher-dimensional arrays, flipud() operates on the first axis (rows). This method is particularly useful for reversing the row order without affecting the individual elements in the rows.


Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits? 
The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. It is a versatile function that allows you to divide an array into a specified number of sub-arrays, even if the array cannot be evenly divided. This makes it especially useful for handling uneven splits, where the number of elements in each sub-array can vary.

Functionality:
Syntax: numpy.array_split(ary, indices_or_sections, axis=0)
ary: The input array to be split.
indices_or_sections: Either the number of splits (an integer) or an array of indices indicating where to split the array.
axis: The axis along which to split the array. By default, it is set to 0 (splitting along rows for 2D arrays).
Handling Uneven Splits:
When the array cannot be evenly divided, array_split() distributes the remaining elements among the sub-arrays as evenly as possible. The first few sub-arrays will contain one more element than the others, ensuring the total number of elements is still preserved.

For example, if you try to split an array of 10 elements into 3 sub-arrays, each sub-array would ideally contain 3 elements. Since 10 is not divisible by 3, two of the sub-arrays will contain 3 elements, and one will contain 4 elements.

Q10.  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
operations
The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. It is a versatile function that allows you to divide an array into a specified number of sub-arrays, even if the array cannot be evenly divided. This makes it especially useful for handling uneven splits, where the number of elements in each sub-array can vary.
Ans)
Functionality:
Syntax: numpy.array_split(ary, indices_or_sections, axis=0)
ary: The input array to be split.
indices_or_sections: Either the number of splits (an integer) or an array of indices indicating where to split the array.
axis: The axis along which to split the array. By default, it is set to 0 (splitting along rows for 2D arrays).
Handling Uneven Splits:
When the array cannot be evenly divided, array_split() distributes the remaining elements among the sub-arrays as evenly as possible. The first few sub-arrays will contain one more element than the others, ensuring the total number of elements is still preserved?

Practical Questions:-

In [1]:
import numpy as np

In [3]:
#1.  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[15 60 58]
 [21 78  6]
 [60 80 32]]

Transposed Array:
[[15 21 60]
 [60 78 80]
 [58  6 32]]


In [4]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array
array_1d = np.arange(1, 11)
print("1D Array:")
print(array_1d)

array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(array_2x5)

array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(array_5x2)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped into 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped into 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [5]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\nArray with Border (6x6):")
print(array_with_border)

Original 4x4 Array:
[[0.06453921 0.63560523 0.06459662 0.46739036]
 [0.86570369 0.45121055 0.21450161 0.96042418]
 [0.40261228 0.34402807 0.22877393 0.43540894]
 [0.54977195 0.13706581 0.17550237 0.20968914]]

Array with Border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.06453921 0.63560523 0.06459662 0.46739036 0.        ]
 [0.         0.86570369 0.45121055 0.21450161 0.96042418 0.        ]
 [0.         0.40261228 0.34402807 0.22877393 0.43540894 0.        ]
 [0.         0.54977195 0.13706581 0.17550237 0.20968914 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [7]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
array = np.arange(10, 65, 5)
print("Array of integers from 10 to 60 with a step of 5:")
print(array)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [8]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
array = np.array(['python', 'numpy', 'pandas'])

uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

print("Original Array:")
print(array)

print("\nUppercase:")
print(uppercase_array)

print("\nLowercase:")
print(lowercase_array)

print("\nTitle Case:")
print(titlecase_array)

print("\nCapitalized:")
print(capitalize_array)

Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


In [9]:
#6.  Generate a NumPy array of words. Insert a space between each character of every word in the array
words_array = np.array(['python', 'numpy', 'pandas'])

spaced_array = np.char.join(' ', words_array)

print("Original Array:")
print(words_array)

print("\nArray with Spaces Between Characters:")
print(spaced_array)

Original Array:
['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [10]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [12]:
#8.  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [13]:
#9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

random_array = np.random.randint(0, 1001, size=100)

primes = [num for num in random_array if is_prime(num)]

print("Original Array:")
print(random_array)

print("\nPrime Numbers in the Array:")
print(primes)

Original Array:
[779 128 935 274  99 156 319 750 564 872  77 925 600 831 276 813 566  40
  33 403 544 528  87 114 768 370 227 699 775  86 348 501 247 522 675 987
 920 463 898 758 609 769 526 719 637 546 983 951 545 470 847 252 578 517
  76 793  68  78 557  93 142 444 495 544  90 609 785 842 536 747 863 498
 838  82 354 634 213 642 400 555 396 373 856 730 469 233 769 315 511 835
 124  11 289 275 153  34 375 674 510  61]

Prime Numbers in the Array:
[227, 463, 769, 719, 983, 557, 863, 373, 233, 769, 11, 61]


In [16]:
#10.  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
temperatures = np.random.randint(20, 35, size=30) 

weekly_averages = np.mean(temperatures.reshape(3, 10), axis=1)

print("Daily Temperatures for the Month:")
print(temperatures)

print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[23 24 21 31 32 20 31 25 27 30 31 32 25 31 29 29 20 30 32 26 28 31 30 20
 33 29 31 20 30 29]

Weekly Averages:
[26.4 28.5 28.1]
